development:
  clients:
    default:
      database: surf_comp_development
      hosts:
        - localhost:27017
      options:

  options:

test:
  clients:
    default:
      database: surf_comp_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
